language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
script:
  - ./mvn clean test
  - bash <(curl -s https://codecov.io/bash)
